name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Brakeman
      uses: devmasx/brakeman-linter-action@v1.0.0
      with: 
        args: --no-exit-on-warn 
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
